Добавил имя и сделал рандомный вывод header__nav
htmlacademy-php/1446917-readme-12 pull request #2
Opened 2022-01-23 17:58 UTC by romawebdev

2022-01-25 15:45 UTC, romawebdev commented
Добавил имя и сделал рандомный вывод header__nav

2022-01-26 06:32 UTC, sterlikoff requested changes
Роман, тут хорошо, только почему то не выводится имя пользователя. Нужно сделать вывод `user_name` в соответствующем месте. Поправь это и будет зачет :)

Еще момент, вижу, тут же стал делать следующее задание. Следует создавать новую ветку для каждого задания.

2022-01-26 07:43 UTC, romawebdev commented
> Роман, тут хорошо, только почему то не выводится имя пользователя. Нужно сделать вывод `user_name` в соответствующем месте. Поправь это и будет зачет :)
> 
> Еще момент, вижу, тут же стал делать следующее задание. Следует создавать новую ветку для каждого задания.

Понял, вернулся в ветку module1-task2 сделал выводу, запушил, я так понимаю pr создавать не нужно новый.
У меня вопрос как теперь с веткой module2-task1 в ней то изменений нет, получаеться мне нужно ее обновить из главного репозитория после того как будет слелан мердж, и решить конфликты?

Со следующим заданием в этой же ветке немного тупанул с непривычки.

2022-01-26 15:30 UTC, sterlikoff approved these changes
Роман, теперь отлично!
Здорово, что получилось разобраться с ветками и убрать здесь следующее задание :)
Зачет!

2022-01-26 15:30 UTC, merged